name: Keep Render Awake

on:
  schedule:
    - cron: '*/14 * * * *' # Runs every 14 minutes
  workflow_dispatch: # Allows you to trigger it manually if needed

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Alfaaz Backend
        run: curl -s https://alfaaz-project.onrender.com/ > /dev/null
